function renderStudents(){
    var el=document.getElementById('students-root');
    if(!Store.students.length){el.innerHTML='<p class="muted">Chưa có học viên nào.</p>';return;}
    el.innerHTML=Store.students.map(function(s){
        var ri=s.rate?formatMoney(s.rate)+'/'+s.rate_minutes+'p':'';
        var grp=Store.groups.find(function(g){return g.id===s.group_id;});
        var grpTag=grp?'<span class="stu-group-tag">👥 '+grp.name+'</span>':'';
        return '<div class="stu-card"><div class="stu-info"><h4>'+s.name+'</h4><p>📚 '+(s.program||'—')+' · 🎯 '+s.level+'</p>'+(ri?'<p class="stu-rate">💰 '+ri+'</p>':'')+(s.review?'<p>💬 '+s.review+'</p>':'')+(s.note?'<p>📝 '+s.note+'</p>':'')+grpTag+'</div><div class="stu-actions"><button class="btn btn-outline btn-sm" onclick="openAssignModal(\''+s.id+'\')">👥 Nhóm</button><button class="btn btn-danger btn-sm" onclick="deleteStudent(\''+s.id+'\')">🗑</button></div></div>';
    }).join('');
}
async function saveStudent(e){e.preventDefault();syncUI('🔄 Lưu...');var obj={user_id:CONFIG.USER_ID,name:document.getElementById('s-name').value,program:document.getElementById('s-program').value,rate:parseInt(document.getElementById('s-rate').value)||0,rate_minutes:parseInt(document.getElementById('s-rate-minutes').value)||60,level:document.getElementById('s-level').value,review:document.getElementById('s-review').value,note:document.getElementById('s-note').value};var r=await db.from('students').insert(obj).select();if(r.error){alert('❌ '+r.error.message);syncUI('❌');return;}Store.students.push(r.data[0]);Store.buildColorMap();document.getElementById('student-form').reset();closeStudentModal();renderStudents();populateDropdown();syncUI('✅ Synced');}
async function deleteStudent(id){if(!confirm('Xóa?'))return;syncUI('🔄...');await db.from('students').delete().eq('id',id);Store.students=Store.students.filter(function(s){return s.id!==id;});Store.buildColorMap();renderStudents();populateDropdown();syncUI('✅ Synced');}
async function confirmAssign(){var sel=document.getElementById('assign-group-select');var gid=sel.value||null;var sid=sel.dataset.studentId;syncUI('🔄...');await db.from('students').update({group_id:gid}).eq('id',sid);var stu=Store.students.find(function(s){return s.id===sid;});if(stu)stu.group_id=gid;closeAssignModal();renderStudents();renderGroups();syncUI('✅ Synced');}
function populateDropdown(){var sel=document.getElementById('f-student');sel.innerHTML='<option value="">-- Chọn --</option>'+Store.students.map(function(s){return'<option value="'+s.id+'">'+s.name+(s.rate?' ('+formatMoney(s.rate)+'/'+s.rate_minutes+'p)':'')+'</option>';}).join('');}
function populateGroupDropdown(){var sel=document.getElementById('f-group');sel.innerHTML='<option value="">-- Chọn nhóm --</option>'+Store.groups.map(function(g){return'<option value="'+g.id+'">'+g.name+(g.rate?' ('+formatMoney(g.rate)+'/'+g.rate_minutes+'p)':'')+'</option>';}).join('');}
function populateQuickDropdowns(){document.getElementById('q-student').innerHTML='<option value="">-- Chọn --</option>'+Store.students.map(function(s){return'<option value="'+s.id+'">'+s.name+'</option>';}).join('');document.getElementById('q-group').innerHTML='<option value="">-- Chọn --</option>'+Store.groups.map(function(g){return'<option value="'+g.id+'">'+g.name+'</option>';}).join('');}
